import type {
  SwitchboardAggregatorsQuery,
  SwitchboardAggregatorsQueryVariables,
} from "@/gql/graphql";
import type { SwitchboardAggregator } from "@/lib/types";

import { useQuery } from "@apollo/client/react";
import { useSuiClientQuery } from "@mysten/dapp-kit";
import { useMemo } from "react";

import { graphql } from "@/gql";
import { loggers } from "@/utils/debug";

const { debugLog, errorLog } = loggers("app:hooks:switchboard-aggregators");

const SWITCHBOARD_AGGREGATOR_TYPE_ID =
  import.meta.env.VITE_SWITCHBOARD_AGGREGATOR_TYPE_ID || "";

/**
 * GraphQL query for Switchboard Aggregator objects
 * Generated by GraphQL Codegen
 */
const SWITCHBOARD_AGGREGATORS_QUERY = graphql(/* GraphQL */ `
  query SwitchboardAggregators($first: Int!, $after: String, $type: String!) {
    objects(first: $first, after: $after, filter: { type: $type }) {
      nodes {
        address
        digest
        asMoveObject {
          contents {
            json
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
`);

interface UseSwitchboardAggregatorsListOptions {
  limit?: number;
  cursor?: string | null;
}

/**
 * Parse a GraphQL object node into a SwitchboardAggregator
 */
function parseAggregatorNode(
  node: NonNullable<SwitchboardAggregatorsQuery["objects"]>["nodes"][number],
): SwitchboardAggregator | null {
  if (!node) {
    return null;
  }

  const json = node.asMoveObject?.contents?.json;

  if (!json || typeof json !== "object" || json === null) {
    return null;
  }

  const typedJson = json as {
    name?: string;
    id?: string;
    authority?: string;
    created_at_ms?: string;
    current_result?: {
      result?: {
        value?: string;
        neg?: boolean;
      };
      timestamp_ms?: string;
    };
  };

  return {
    id: typedJson.id || String(node.address),
    name: typedJson.name || "Unknown",
    address: String(node.address),
    authority: typedJson.authority || "",
    created_at_ms: typedJson.created_at_ms || "0",
    current_result: typedJson.current_result
      ? {
          result: {
            value: typedJson.current_result.result?.value || "0",
            neg: typedJson.current_result.result?.neg || false,
          },
          timestamp_ms: typedJson.current_result.timestamp_ms || "0",
        }
      : undefined,
  };
}

/**
 * Hook to list all Switchboard Aggregator objects using GraphQL
 * Supports pagination and filtering by type
 *
 * Use this hook when you need to browse/search all aggregators.
 *
 * @example
 * ```tsx
 * const { aggregators, isLoading, pagination } = useSwitchboardAggregatorsList({
 *   limit: 20,
 *   cursor: null,
 * });
 * ```
 */
export function useSwitchboardAggregatorsList(
  options: UseSwitchboardAggregatorsListOptions = {},
) {
  const { limit = 20, cursor = null } = options;

  const {
    data,
    loading: isLoading,
    error: queryError,
    networkStatus,
  } = useQuery<
    SwitchboardAggregatorsQuery,
    SwitchboardAggregatorsQueryVariables
  >(SWITCHBOARD_AGGREGATORS_QUERY, {
    variables: {
      first: limit,
      after: cursor,
      type: SWITCHBOARD_AGGREGATOR_TYPE_ID,
    },
    skip:
      !SWITCHBOARD_AGGREGATOR_TYPE_ID || !import.meta.env.VITE_SUI_GRAPHQL_URL,
    errorPolicy: "all", // Return partial data even on errors
    fetchPolicy: "cache-and-network",
    notifyOnNetworkStatusChange: true,
  });

  // Parse aggregators from GraphQL response
  const aggregators = useMemo(() => {
    if (!data?.objects?.nodes) {
      return [];
    }

    const parsed: SwitchboardAggregator[] = [];

    for (const node of data.objects.nodes) {
      const aggregator = parseAggregatorNode(node);

      if (aggregator) {
        parsed.push(aggregator);
      }
    }

    debugLog("Parsed %d Switchboard aggregators from GraphQL", parsed.length);

    return parsed;
  }, [data]);

  // Extract pagination info - always return it even if aggregators array is empty
  // This is important for client-side filtering: if current page has no matches
  // but hasNextPage is true, we should still show pagination controls
  const pagination = useMemo(() => {
    const pageInfo = data?.objects?.pageInfo;

    return {
      hasNextPage: pageInfo?.hasNextPage ?? false,
      nextCursor: pageInfo?.endCursor ?? null,
    };
  }, [data]);

  // Convert Apollo error to Error object
  const error = useMemo(() => {
    if (queryError) {
      errorLog(
        "GraphQL error fetching Switchboard aggregators: %O",
        queryError,
      );

      return queryError instanceof Error
        ? queryError
        : new Error(String(queryError));
    }

    return null;
  }, [queryError]);

  // isFetching is true when networkStatus indicates a fetch is in progress
  const isFetching = networkStatus === 2 || networkStatus === 4; // loading or refetching

  return { aggregators, isLoading, isFetching, error, pagination };
}

/**
 * Data structure for Switchboard Aggregator real-time data
 */
export interface SwitchboardAggregatorData {
  timestamp_ms: number | null;
  price: string | null;
}

/**
 * Hook to batch query multiple Switchboard Aggregator objects by addresses
 * Returns real-time data (price, timestamp) for the specified addresses
 *
 * Use this hook when you have a list of aggregator addresses and need their current data.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useSwitchboardAggregatorsByAddresses([
 *   "0x123...",
 *   "0x456...",
 * ]);
 * const aggregatorData = data.get("0x123...");
 * ```
 */
export function useSwitchboardAggregatorsByAddresses(addresses: string[]): {
  data: Map<string, SwitchboardAggregatorData>;
  isLoading: boolean;
  error: Error | null;
} {
  const {
    data: aggregatorObjects,
    isLoading,
    error: queryError,
  } = useSuiClientQuery(
    "multiGetObjects",
    {
      ids: addresses,
      options: {
        showContent: true,
      },
    },
    {
      enabled: addresses.length > 0,
      staleTime: 30000,
    },
  );

  // Parse switchboard data into a map
  const data = useMemo(() => {
    const map = new Map<string, SwitchboardAggregatorData>();

    if (!aggregatorObjects || addresses.length === 0) {
      return map;
    }

    for (let i = 0; i < aggregatorObjects.length; i++) {
      const obj = aggregatorObjects[i];
      const address = addresses[i];

      if (!address) {
        continue;
      }

      if (!obj?.data || !("content" in obj.data)) {
        map.set(address, { timestamp_ms: null, price: null });
        continue;
      }

      const content = obj.data.content;

      if (
        !content ||
        content.dataType !== "moveObject" ||
        !("fields" in content)
      ) {
        map.set(address, { timestamp_ms: null, price: null });
        continue;
      }

      const fields = content.fields as Record<string, unknown>;
      const currentResult = fields.current_result as
        | {
            fields?: {
              timestamp_ms?: string | number;
              result?: {
                fields?: {
                  value?: string;
                  neg?: boolean;
                };
              };
            };
          }
        | undefined;

      if (!currentResult?.fields) {
        map.set(address, { timestamp_ms: null, price: null });
        continue;
      }

      const timestampMs = currentResult.fields.timestamp_ms;
      let parsedTimestamp: number | null = null;

      if (typeof timestampMs === "string") {
        const parsed = parseInt(timestampMs, 10);

        if (!isNaN(parsed)) {
          parsedTimestamp = parsed;
        }
      } else if (typeof timestampMs === "number") {
        parsedTimestamp = timestampMs;
      }

      // Extract price from result.value
      const result = currentResult.fields.result;
      let price: string | null = null;

      if (result && typeof result === "object" && "fields" in result) {
        const resultFields = result.fields as {
          value?: string;
          neg?: boolean;
        };

        if (resultFields.value) {
          price = resultFields.value;
        }
      }

      map.set(address, {
        timestamp_ms: parsedTimestamp,
        price: price,
      });
    }

    debugLog("Parsed %d Switchboard aggregators from batch query", map.size);

    return map;
  }, [aggregatorObjects, addresses]);

  const error = useMemo(() => {
    if (queryError) {
      errorLog("Error batch querying Switchboard Aggregators: %O", queryError);

      return queryError instanceof Error
        ? queryError
        : new Error(String(queryError));
    }

    return null;
  }, [queryError]);

  return { data, isLoading, error };
}
