import type {
  SwitchboardAggregatorsQuery,
  SwitchboardAggregatorsQueryVariables,
} from "@/gql/graphql";
import type { SwitchboardAggregator } from "@/lib/types";

import { useQuery } from "@apollo/client/react";
import { useMemo } from "react";

import { graphql } from "@/gql";
import { loggers } from "@/utils/debug";

const { debugLog, errorLog } = loggers("app:hooks:switchboard-aggregators");

const SWITCHBOARD_AGGREGATOR_TYPE_ID =
  import.meta.env.VITE_SWITCHBOARD_AGGREGATOR_TYPE_ID || "";

/**
 * GraphQL query for Switchboard Aggregator objects
 * Generated by GraphQL Codegen
 */
const SWITCHBOARD_AGGREGATORS_QUERY = graphql(/* GraphQL */ `
  query SwitchboardAggregators($first: Int!, $after: String, $type: String!) {
    objects(first: $first, after: $after, filter: { type: $type }) {
      nodes {
        address
        digest
        asMoveObject {
          contents {
            json
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
`);

interface UseSwitchboardAggregatorsOptions {
  limit?: number;
  cursor?: string | null;
}

/**
 * Parse a GraphQL object node into a SwitchboardAggregator
 */
function parseAggregatorNode(
  node: NonNullable<SwitchboardAggregatorsQuery["objects"]>["nodes"][number],
): SwitchboardAggregator | null {
  if (!node) {
    return null;
  }

  const json = node.asMoveObject?.contents?.json;

  if (!json || typeof json !== "object" || json === null) {
    return null;
  }

  const typedJson = json as {
    name?: string;
    id?: string;
    authority?: string;
    created_at_ms?: string;
    current_result?: {
      result?: {
        value?: string;
        neg?: boolean;
      };
      timestamp_ms?: string;
    };
  };

  return {
    id: typedJson.id || node.address,
    name: typedJson.name || "Unknown",
    address: node.address,
    authority: typedJson.authority || "",
    created_at_ms: typedJson.created_at_ms || "0",
    current_result: typedJson.current_result
      ? {
          result: {
            value: typedJson.current_result.result?.value || "0",
            neg: typedJson.current_result.result?.neg || false,
          },
          timestamp_ms: typedJson.current_result.timestamp_ms || "0",
        }
      : undefined,
  };
}

/**
 * Hook to query Switchboard Aggregator objects using GraphQL with Apollo Client
 * Supports pagination
 *
 * Note: Pagination info is always returned even if filtered results are empty,
 * because the next page might contain matching results after client-side filtering.
 */
export function useSwitchboardAggregators(
  options: UseSwitchboardAggregatorsOptions = {},
) {
  const { limit = 20, cursor = null } = options;

  const {
    data,
    loading: isLoading,
    error: queryError,
    networkStatus,
  } = useQuery<
    SwitchboardAggregatorsQuery,
    SwitchboardAggregatorsQueryVariables
  >(SWITCHBOARD_AGGREGATORS_QUERY, {
    variables: {
      first: limit,
      after: cursor,
      type: SWITCHBOARD_AGGREGATOR_TYPE_ID,
    },
    skip:
      !SWITCHBOARD_AGGREGATOR_TYPE_ID || !import.meta.env.VITE_SUI_GRAPHQL_URL,
    errorPolicy: "all", // Return partial data even on errors
    fetchPolicy: "cache-and-network",
    notifyOnNetworkStatusChange: true,
  });

  // Parse aggregators from GraphQL response
  const aggregators = useMemo(() => {
    if (!data?.objects?.nodes) {
      return [];
    }

    const parsed: SwitchboardAggregator[] = [];

    for (const node of data.objects.nodes) {
      const aggregator = parseAggregatorNode(node);

      if (aggregator) {
        parsed.push(aggregator);
      }
    }

    debugLog("Parsed %d Switchboard aggregators from GraphQL", parsed.length);

    return parsed;
  }, [data]);

  // Extract pagination info - always return it even if aggregators array is empty
  // This is important for client-side filtering: if current page has no matches
  // but hasNextPage is true, we should still show pagination controls
  const pagination = useMemo(() => {
    const pageInfo = data?.objects?.pageInfo;

    return {
      hasNextPage: pageInfo?.hasNextPage ?? false,
      nextCursor: pageInfo?.endCursor ?? null,
    };
  }, [data]);

  // Convert Apollo error to Error object
  const error = useMemo(() => {
    if (queryError) {
      errorLog(
        "GraphQL error fetching Switchboard aggregators: %O",
        queryError,
      );

      return queryError instanceof Error
        ? queryError
        : new Error(String(queryError));
    }

    return null;
  }, [queryError]);

  // isFetching is true when networkStatus indicates a fetch is in progress
  const isFetching = networkStatus === 2 || networkStatus === 4; // loading or refetching

  return { aggregators, isLoading, isFetching, error, pagination };
}
