import type {
  ShareRatioEventsQuery,
  ShareRatioEventsQueryVariables,
} from "@/gql/graphql";

import { useState, useCallback, useEffect } from "react";
import { useQuery } from "@apollo/client/react";

import { graphql } from "@/gql";

// Use initial package ID for querying events (events are tied to initial package)
const VOLO_VAULT_PACKAGE_ID =
  import.meta.env.VITE_VOLO_VAULT_PACKAGE_ID_INITIAL || "";

export interface ShareRatioHistoryItem {
  shareRatio: bigint;
  timestamp: number;
  transactionDigest: string;
}

/**
 * GraphQL query for ShareRatioUpdated events
 * Generated by GraphQL Codegen
 */
const SHARE_RATIO_EVENTS_QUERY = graphql(/* GraphQL */ `
  query ShareRatioEvents($first: Int!, $eventType: String!, $after: String) {
    events(first: $first, filter: { type: $eventType }, after: $after) {
      nodes {
        transaction {
          digest
        }
        timestamp
        contents {
          json
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
`);

/**
 * Parse a single event node and convert it to ShareRatioHistoryItem if it matches the vault
 */
function parseEventNode(
  node: NonNullable<ShareRatioEventsQuery["events"]>["nodes"][number],
  vaultId: string,
): ShareRatioHistoryItem | null {
  if (!node) {
    return null;
  }

  // Access queried fields directly
  if (!node.contents?.json || !node.transaction?.digest) {
    return null;
  }

  const json = node.contents.json;
  const timestamp = node.timestamp;

  // Filter by vault_id (events are already filtered by type on server)
  if (
    typeof json === "object" &&
    json !== null &&
    "vault_id" in json &&
    "share_ratio" in json
  ) {
    const eventVaultId = String(json.vault_id);

    // Only include events for this vault
    if (eventVaultId === vaultId) {
      const shareRatioValue = json.share_ratio;

      if (shareRatioValue === undefined) {
        return null;
      }

      let shareRatio: bigint;

      // Convert share_ratio (u256) to BigInt
      if (typeof shareRatioValue === "string") {
        shareRatio = BigInt(shareRatioValue);
      } else if (typeof shareRatioValue === "number") {
        shareRatio = BigInt(shareRatioValue);
      } else if (Array.isArray(shareRatioValue)) {
        // If it's an array (bytes representation), convert it
        shareRatio = 0n;

        for (let i = shareRatioValue.length - 1; i >= 0; i--) {
          shareRatio = shareRatio * 256n + BigInt(shareRatioValue[i] || 0);
        }
      } else {
        return null; // Skip invalid data
      }

      // Parse timestamp (DateTime is returned as ISO string)
      let parsedTimestamp = 0;

      if (timestamp) {
        if (typeof timestamp === "string") {
          parsedTimestamp = new Date(timestamp).getTime();
        } else if (typeof timestamp === "number") {
          parsedTimestamp = timestamp;
        }
      }

      const transactionDigest = node.transaction.digest;

      return {
        shareRatio,
        timestamp: parsedTimestamp,
        transactionDigest,
      };
    }
  }

  return null;
}

/**
 * Hook to query share ratio history from ShareRatioUpdated events using GraphQL
 * Supports pagination with "load more" functionality
 *
 * @param vaultId - The vault object ID
 * @param pageSize - Number of events to fetch per page (default: 50, max: 50)
 */
export function useVaultShareRatioHistoryGraphQL(
  vaultId: string | null,
  pageSize: number = 50, // Max page size is 50
) {
  const eventType = VOLO_VAULT_PACKAGE_ID
    ? `${VOLO_VAULT_PACKAGE_ID}::vault::ShareRatioUpdated`
    : "";

  // Track accumulated history and cursor
  const [accumulatedHistory, setAccumulatedHistory] = useState<
    ShareRatioHistoryItem[]
  >([]);
  const [endCursor, setEndCursor] = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(false);
  const [oldestTimestamp, setOldestTimestamp] = useState<number | null>(null);

  const {
    data,
    loading: isLoading,
    error,
    refetch,
    fetchMore,
  } = useQuery<ShareRatioEventsQuery, ShareRatioEventsQueryVariables>(
    SHARE_RATIO_EVENTS_QUERY,
    {
      variables: {
        first: pageSize,
        eventType,
        after: null,
      },
      skip:
        !vaultId ||
        !VOLO_VAULT_PACKAGE_ID ||
        !eventType ||
        !import.meta.env.VITE_SUI_GRAPHQL_URL,
      errorPolicy: "all", // Return partial data even on errors
      fetchPolicy: "cache-and-network",
      notifyOnNetworkStatusChange: true,
    },
  );

  // Process data when it changes
  useEffect(() => {
    if (!vaultId || !data?.events?.nodes) {
      return;
    }

    // Parse and filter events for this vault
    const newItems: ShareRatioHistoryItem[] = [];

    for (const node of data.events.nodes) {
      const item = parseEventNode(node, vaultId);

      if (item) {
        newItems.push(item);
      }
    }

    // Update accumulated history
    setAccumulatedHistory((prev) => {
      // Combine and deduplicate by transactionDigest
      const combined = [...prev, ...newItems];
      const seen = new Set<string>();

      return combined
        .filter((item) => {
          if (seen.has(item.transactionDigest)) {
            return false;
          }

          seen.add(item.transactionDigest);

          return true;
        })
        .sort((a, b) => b.timestamp - a.timestamp);
    });

    // Update pagination state
    const pageInfo = data.events.pageInfo;

    setEndCursor(pageInfo?.endCursor ?? null);
    setHasMore(pageInfo?.hasNextPage ?? false);

    // Update oldest timestamp
    if (newItems.length > 0) {
      const timestamps = newItems.map((item) => item.timestamp).filter(Boolean);

      if (timestamps.length > 0) {
        const oldest = Math.min(...timestamps);

        setOldestTimestamp((prev) =>
          prev === null ? oldest : Math.min(prev, oldest),
        );
      }
    }
  }, [data, vaultId]);

  // Load more function
  const loadMore = useCallback(async () => {
    if (!hasMore || !endCursor || isLoading || !vaultId || !eventType) {
      return;
    }

    await fetchMore({
      variables: {
        first: pageSize,
        eventType,
        after: endCursor,
      },
    });
  }, [hasMore, endCursor, isLoading, vaultId, eventType, pageSize, fetchMore]);

  // Reset accumulated history when vaultId changes
  useEffect(() => {
    setAccumulatedHistory([]);
    setEndCursor(null);
    setHasMore(false);
    setOldestTimestamp(null);
  }, [vaultId]);

  return {
    history: accumulatedHistory,
    isLoading,
    error,
    refetch,
    loadMore,
    hasMore,
    oldestTimestamp,
    isGraphQLAvailable: !!import.meta.env.VITE_SUI_GRAPHQL_URL,
  };
}
